fix(grunt): watch task failing due to dependency error
Error: Cannot find module 'coffeelint'
Warning: Task "coffeelint" not found. Use --force to continue.